### ISSUE TITLE
setAliasAndTags  callback  no response ? 

### ISSUE THREAD

**Issue by iielse** [jpush/jpush-docs#491]
```
JPushInterface.setAliasAndTags(getApplicationContext(), alias, null, mAliasCallback);
```
该方法是不是做过'保护'，回调都不会被触发了？ 我希望收到一个回调，错误码可以是其它的啊。

**Comment by helperhaps** [comment]
请去[极光社区](community.jiguang.cn) 提问业务相关问题

**Comment by iielse** [comment]
谢谢，不过你这个`极光社区`的超链接地址配错了。
配成了 `https://github.com/jpush/jpush-docs/issues/community.jiguang.cn`

**Comment by helperhaps** [comment]
确实，复制的时候没有加 `https://`，Redcarpt 就解析成站内链接了，已修改
