### ISSUE TITLE
首次安装Android APP的时候报ANR，

### ISSUE THREAD

**Issue by ml-bright** [jpush/jpush-docs#592]
// 此处以JPush 3.0.5 版本为例。
    compile 'cn.jiguang.sdk:jpush:3.0.8'
    // 此处以JCore 1.1.2 版本为例。
    compile 'cn.jiguang.sdk:jcore:1.1.6'

qua = unknown
versionName = 3.0.5
versionCode = 20
imei = 99000628646756
uid = uid
network = unknown
model = MI 4LTE
api-level = 23 6.0.1
cpu-core = 4
process = com.xingluo.mpa:pushcore
freeMemory = 801932
totalMemory = 2931804
time = 1466
thread-time = 6
time-start = 09-18 15:04:16.801
time-end = 09-18 15:04:18.267
cpu-busy = false
cpu-rate = null
stack = 09-18 15:04:17.617
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor$(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:970)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(
AbstractQueuedSynchronizer.java:1278)
java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
android.app.SharedPreferencesImpl$EditorImpl$1.run(SharedPreferencesImpl.java:366)
android.app.QueuedWork.waitToFinish(QueuedWork.java:88)
android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3049)
android.app.ActivityThread.access$2300(ActivityThread.java:153)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:5524)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by helperhaps** [comment]
产品问题请到 https://community.jiguang.cn/ 提问，这个仓库只维护文档
