### ISSUE TITLE
Android极光推送分生产环境和开发方案？

### ISSUE THREAD

**Issue by mysiga** [jpush/jpush-docs#604]
希望能提供一个极光推送Android区分生产和开发环境的方案。
  分包名解决方案不可行，在已使用其他第三方sdk情况分包名切换环境成本大。
希望Android推送提供一个同一个包名区分不同环境结局方案。

**Comment by helperhaps** [comment]
业务问题请去 https://community.jiguang.cn/ 这里反馈，本仓库只和文档结构相关
