### ISSUE TITLE
AndroidStudio3.0Beta6上无法通过jcenter集成JMessage

### ISSUE THREAD

**Issue by nmgzhangrl** [jpush/jpush-docs#607]
Android上，通过jcenter 自动集成JMessage的时候

在AndroidStudio3.0Beta6（android-studio-ide-171.4333198-windows.zip）上，
jmessage-android_v2.2.1.jar包无法集成进来，无法找到JMessageClient

在AndroidStudio2.3.3上没问题。

**Comment by helperhaps** [comment]
请去 [极光社区](https://community.jiguang.cn) 提问业务相关问题，或在相应项目的仓库中提 issue
