### ISSUE TITLE
模块化时，如果将jpush依赖放在子module中，则依赖他的包全部需要在gradle中manifestPlaceholders

### ISSUE THREAD

**Issue by jsbsdbd1025** [jpush/jpush-docs#608]
模块化时，如果将jpush依赖放在子module中，则依赖他的包全部需要在gradle中manifestPlaceholders
能够做到配置一处即可吗
若某module没配置manifestPlaceholders   
报错
Attribute category#${JPUSH_PKGNAME}@name at manifestMerger8093836428274636398.xml requires a placeholder substitution but no value for <JPUSH_PKGNAME> is provided.

**Comment by helperhaps** [comment]
请去 [极光社区](https://community.jiguang.cn) 提问业务相关问题，或在相应项目的仓库中提 issue
