### ISSUE TITLE
主页文档web login 那里少了一个)

### ISSUE THREAD

**Issue by gogobody** [jpush/jpush-docs#660]
`JIM.login({
    'username' : '<login username>',
    'password' : '<login password>'
}).onSuccess(function(data) {
     //data.code 返回码
     //data.message 描述
}.onFail(function(data){ #这一行onFail前面
  //同上
});`

**Comment by helperhaps** [comment]
请问具体是哪里

**Comment by helperhaps** [comment]
有问题可以去 [极光开发者社区](https://community.jiguang.cn/)反馈
