### ISSUE TITLE
极光推送iOS SDK 3.0.6 crash ,极光的SDK不支持i386架构的模拟器，是否提供支持i386架构支持

### ISSUE THREAD

**Issue by JustinYangJing** [jpush/jpush-docs#674]
0 CoreFoundation | ___exceptionPreprocess + 124
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSException initWithCoder:]
3 Foundation | +[NSString stringWithCString:encoding:] + 100
4 ------- | -[JPUSHAddressController getAddressByHostDomain:] + 548
5 ------- | -[JPUSHAddressController getSisHostAddress:] + 176
6 ------- | -[JPUSHAddressController sendSisRequest] + 140
7 ------- | -[JPUSHSessionController connect] + 196
8 ------- | -[JPUSHSessionController setup] + 260
9 ------- | +[JCOREInterface trySetupSession] + 80
10 ------- | -[JPUSHClientController updateDeviceToken:] + 360
11 Foundation | ___NSThreadPerformPerform + 340
12 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
13 CoreFoundation | ___CFRunLoopDoSources0 + 524
14 CoreFoundation | ___CFRunLoopRun + 804
15 CoreFoundation | CFRunLoopRunSpecific + 444
16 CoreFoundation | CFRunLoopRun + 112
17 ------- | -[JPUSHThread clientThreadMain] + 100
18 Foundation | ___NSThread__start__ + 1024
19 libsystem_pthread.dylib | __pthread_body + 240
20 libsystem_pthread.dylib | __pthread_body
21 libsystem_pthread.dylib | thread_start + 4

crash 原因
#9 Thread
NSInvalidArgumentException
*** +[NSString stringWithCString:encoding:]: NULL cString
极光3.0.6的版本由于这个原因产生大量crash

极光的SDK不支持i386架构的模拟器，是否提供支持i386架构支持，由于极光SDK 不能跑模拟器真的不方便

**Comment by helperhaps** [comment]
请去[极光开发者社区](https://community.jiguang.cn/)提问
