### ISSUE TITLE
极光推送3.1.0 继承activity的类时会有服务泄露的问题

### ISSUE THREAD

**Issue by LazyDemo** [jpush/jpush-docs#683]

**Comment by iielse** [comment]
![c vmx pth73t9g qzr ti](https://user-images.githubusercontent.com/7521943/33929463-92517248-e024-11e7-9c84-00befeeae237.png)

![4o0 n6 dz 32 l liaow h](https://user-images.githubusercontent.com/7521943/33929479-9cb85d3c-e024-11e7-89c9-31a1455f71f8.png)

我这里也撞见一个， 

顺带，请问 `janalytics` 什么时候出， 好想要

**Comment by iielse** [comment]
额，不好意思，看到了  compile 'cn.jiguang.sdk:janalytics:1.1.1'
刚才以为只有jar包。 比某盟 集成起来方便多了。

**Comment by ToGallop** [comment]
'cn.jiguang.sdk:jpush:3.0.9'
 'cn.jiguang.sdk:jcore:1.1.7'
我也遇到同样的问题。LeakCanary检测到内存泄漏
一开始只是提示：一个线程和一个activity实例
（named 'pool-5-thread-1'）,后来才出现极光的问题。
请问这个怎么解决？

**Comment by helperhaps** [comment]
请去[极光开发者社区](https://community.jiguang.cn/)提问
