### ISSUE TITLE
sdk现在支持android8.0吗？android 8.0 对应用后台执行有较大的变更。不知道极光sdk现在适配了没有？

### ISSUE THREAD

**Issue by hugbio** [jpush/jpush-docs#690]
android 8.0 对后台应用的后台服务和隐式广播 变更比较大。极光sdk现在适配了没有？如果适配了。集成sdk最小版本应该是多少？

**Comment by helperhaps** [comment]
请去[极光开发者社区](https://community.jiguang.cn/)提问
