### ISSUE TITLE
新别名alias与标签tag接口 没有地方接收返回啊

### ISSUE THREAD

**Issue by caosiqiao4000** [jpush/jpush-docs#697]
https://docs.jiguang.cn/jpush/client/Android/android_api/#aliastag
旧接口里
public static void setAliasAndTags(Context context, 
                                   String alias, 
                                   Set<String> tags, 
                                   TagAliasCallback callback);
能在TagAliasCallback 里接收接口设置的结果,
但新别名alias与标签tag接口   
public static void setAlias(Context context, int sequence, String alias);
public static void setTags(Context context, int sequence,Set<String> tags);
方法返回为void 也没有接口回调
怎么知道设置结果 ?????

**Comment by helperhaps** [comment]
请去[极光社区](https://community.jiguang.cn) 提问业务相关问题，或在相应项目的仓库中提 issue
